- id: check-case-conflict
  name: Check for case conflicts
  description: Check for files that would conflict in case-insensitive filesystems
  entry: check-case-conflict
- id: check-docstring-first
  name: Check docstring is first
  description: Checks a common error of defining a docstring after code.
  entry: check-docstring-first
  language: python
  types: [python]
- id: check-merge-conflict
  name: Check for merge conflicts
  description: Check for files that contain merge conflict strings.
  entry: check-merge-conflict
  language: python
  types: [text]
- id: check-yaml
  name: Check Yaml
  description: This hook checks yaml files for parseable syntax.
  entry: check-yaml
  language: python
  types: [yaml]
- id: flake8
  name: Flake8
  description: This hook runs flake8.
  entry: flake8
  language: python
  types: [python]
- id: trailing-whitespace
  name: Trim Trailing Whitespace
  description: This hook trims trailing whitespace.
  entry: trailing-whitespace-fixer
  language: python
  types: [text]