- repo: https://github.com/sagunji/python-starter-kit.git
  hooks:
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
    - id: flake8
    - id: trailing-whitespace